### ISSUE TITLE
Reactive form patch value makes the form dirty

### ISSUE THREAD

**Issue by mkdudeja** [stevermeister/ngx-wig#102]
Hi,

Ngx-wig implementation with reactive form controls.

Patching a value using `patchValue` makes the form dirty, which shouldn't be the case.

Following is the stackblitz implementation:
https://stackblitz.com/edit/ngx-wig-sample7-u7huhp?file=src%2Fapp.ts

Thanks,
Manish

**Comment by stevermeister** [comment]
Hi @mkdudeja,
thank you for detailed feedback with an example! 

I've made PR with a fix
https://github.com/stevermeister/ngx-wig/pull/109/files

**Comment by stevermeister** [comment]
please use version ngx-wig@2.1.3
