### ISSUE TITLE
feature request: Emoji custom button

### ISSUE THREAD

**Issue by DanielChuDC** [stevermeister/ngx-wig#112]
Hi @stevermeister, thank you for writing this awesome library in angular.

Do you have any idea to add in a emoji function? (maybe a emoji button... or)

One possible repo is [ngx-quill](https://github.com/KillerCodeMonkey/ngx-quill) and it is using [quill emoji](https://github.com/contentco/quill-emoji)

**Comment by bampakoa** [comment]
@DanielChuDC do you mean how one should implement such a functionality in the library?

**Comment by DanielChuDC** [comment]
Yup! I am not sure how to add emoji function...

My ultimate goal is to able to post message to telegram with emoji 👍

**Comment by bampakoa** [comment]
Check out [this](https://github.com/stevermeister/ngx-wig#adding-own-buttons) guide on how to add your custom button.

**Comment by DanielChuDC** [comment]
Thank you @bampakoa. I read that guide but I am not sure how to implement that function.

**Comment by DanielChuDC** [comment]
not adding button. Is how to include emoji at the button.

**Comment by DanielChuDC** [comment]
Found a emoji github: https://github.com/TypeCtrl/ngx-emoji-mart/ , which compatible with angular 9. Hope it helps someone's life
