### ISSUE TITLE
Roadmap: Update to Angular 9

### ISSUE THREAD

**Issue by DanielChuDC** [stevermeister/ngx-wig#113]
Hi, Do you have a plan for upgrading it to support angular 9?
 
If not, how can I help with it?

**Comment by bampakoa** [comment]
@DanielChuDC you could fork the repo and try to upgrade it using the `ng update` command of the Angular CLI. After upgrade, make sure that you check all tests that pass. If you need any further assistance I would be happy to help 😃

**Comment by DanielChuDC** [comment]
ok! thank you

**Comment by stevermeister** [comment]
@DanielChuDC do you have any difficulties with Angular9?

**Comment by MPapst** [comment]
Hi,
I tried an update of the library to Angular 9 and provided an pr.

I needed to change the provider function of `NgxWigModule` that provides the button Library to an inline function, because of a weird compiler issue that is related to angular 9:
```
> Undecorated classes with DI migration.
  As of Angular 9, it is no longer supported to use Angular DI on a class that does not have an Angular decorator.
  Read more about this here: https://v9.angular.io/guide/migration-undecorated-classes

    This migration uses the Angular compiler internally and therefore projects that no longer build successfully after the update cannot run the migration. Please ensure there are no AOT compilation errors and rerun the migration. The following project failed: src/tsconfig.app.json
    Error: error TS100: Error during template compile of 'AppModule'
      Function calls are not supported in decorators but 'provideButtons' was called in 'NgxWigModule'
        'NgxWigModule' calls 'provideButtons'.


    Could not migrate all undecorated classes that use dependency
    injection. Some project targets could not be analyzed due to
    TypeScript program failures.
```

Tests are running fine, linting is having 2 issues (has been 4), I think the type can simply be changed to an interface, but I'm not 100% sure about the side effects:
```
ngx-wig/projects/ngx-wig/src/lib/config.ts[6, 13]: Use an interface instead of a type literal.
ngx-wig/projects/ngx-wig/src/lib/config.ts[14, 13]: Use an interface instead of a type literal.
```

**Comment by stevermeister** [comment]
Version 9.0.0 published

**Comment by MPapst** [comment]
@stevermeister do you plan to update the npm package?

**Comment by stevermeister** [comment]
yes, it's done now.
sorry, forgot to do it right after the merge.

**Comment by stevermeister** [comment]
https://www.npmjs.com/package/ngx-wig/v/9.0.0
