### ISSUE TITLE
Check with ngcc compiler

### ISSUE THREAD

**Issue by bampakoa** [stevermeister/ngx-wig#115]
@stevermeister is there any chance that you have checked the library with the ngcc compiler https://github.com/angular/ngcc-validation?

**Comment by stevermeister** [comment]
oh, wow, not yet

**Comment by stevermeister** [comment]
added - https://github.com/angular/ngcc-validation/pull/1164

**Comment by stevermeister** [comment]
looks like we have some problems :(

**Comment by bampakoa** [comment]
@stevermeister I can see the progress of the PR and it looks good! We are close! If you any help just ping me 😄

**Comment by stevermeister** [comment]
I hope I can manage it :)
fighting with `yarn.lock` conflicts

**Comment by stevermeister** [comment]
done :)
