### ISSUE TITLE
Automate tests using CI

### ISSUE THREAD

**Issue by bampakoa** [stevermeister/ngx-wig#117]
@stevermeister I have noticed that the repo has integration with Travis CI. How about pipe tests in each PR through Travis?

**Comment by stevermeister** [comment]
that's a good idea, I thought it's already there :) 
I'm also thinking maybe migrate it to GitHub actions, what do you think?

**Comment by bampakoa** [comment]
@stevermeister you are right! It is already there and I missed it 🙄 

I have never used GitHub actions before. What additional value would it give to the already workflow of Travis?

**Comment by stevermeister** [comment]
some ideas about GH Actions: 
- I'm using Travis CI only for this project, it's quite hard to maintain
- GH Actions sounds like more native solutions and less external tools
- Functionality is pretty much the same

**Comment by bampakoa** [comment]
I like the idea of having all tooling inside the Github ecosystem. Sounds good for me!
