### ISSUE TITLE
header button

### ISSUE THREAD

**Issue by veteran1** [stevermeister/ngx-wig#121]
Hello, 
is the header list (h1...h6) already implemented in ngx-wig?
How can i add heading to the text.
Thanks

**Comment by bampakoa** [comment]
@veteran1 this feature is not currently baked in the library. However, you could create a plugin for this. Check out [this](https://github.com/stevermeister/ngx-wig#adding-own-buttons) guide how to do it 😃

**Comment by veteran1** [comment]
ok, i will take look,
thanks for your feedback

**Comment by arcadius** [comment]
@veteran1 , any update on this?

**Comment by veteran1** [comment]
@arcadius, no I did not create the plugin since it was not a mandatory requirement for me.
