### ISSUE TITLE
Error after migration to Angular 9

### ISSUE THREAD

**Issue by ghost** [stevermeister/ngx-wig#122]
Do you know how to fix this issue?

ERROR in node_modules/ngx-wig/lib/ngx-wig.component.d.ts:40:18 - error TS2314: Generic type 'ɵɵFactoryDef' requires 1 type argument(s).

40     static ɵfac: i0.ɵɵFactoryDef<NgxWigComponent, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/ngx-wig/lib/ngx-wig.component.d.ts:41:18 - error TS2314: Generic type 'ɵɵComponentDefWithMeta' requires 6 type argument(s).

41     static ɵcmp: i0.ɵɵComponentDefWithMeta<NgxWigComponent, "ngx-wig", never, { "content": "content"; "placeholder": "placeholder"; "buttons": "buttons"; "disabled": "disabled"; }, { "contentChange": "contentChange"; }, never, never>;

**Comment by bampakoa** [comment]
@minchomilev could you please share more details? When do you get this error? How do you use the library? Setting up a Stackblitz demo or some other means would be more than helpful.

**Comment by minchopm** [comment]
I am getting this issue during compile time when I am building the app with Angular Ivy compiler. 
Tested with version 9.1.0 and 9.0.0 - same result
few weeks ago I was using v ^8.0.0 with angular 9 and it was working fine.
when I serve the app there is no such kind of issue.
the case is this one:
properly injected the: NgxWigModule into imports[] of @NgModule

<ngx-wig  [formControl]="text"></ngx-wig>

**Comment by bampakoa** [comment]
@minchopm I could not replicate your issue locally. Could you please try to remove `node_modules` folder and `npm install` again? Also, make sure that you use Typescript 3.8.x

**Comment by minchomilev** [comment]
With Angular 9.1 the issue is not existing. Probably there is a bug in Angular 9.0. Thanks.
