### ISSUE TITLE
Can we use table and image button?

### ISSUE THREAD

**Issue by vinusorout** [stevermeister/ngx-wig#125]
We want to include two buttons
1. Table: by clicking the table button user should be able to choose rows and columns of table, and finally this should insert a table.
2. Image: User should be able to upload image, and application should upload the image in base64 format.

Please let us know if it is possible if yes how we can achieve this?

**Comment by stevermeister** [comment]
@vinusorout that's not what you have out of the box, but you always can create your own plugin and do content manipulation
