### ISSUE TITLE
Can't compile with angular i18n

### ISSUE THREAD

**Issue by veteran1** [stevermeister/ngx-wig#126]
Hello,
I tried to implement the native i18n module in my application, but when I run `ng xi18n` in the terminal, I get this error:

ERROR in Unexpected value 'NgxWigModule in C:/workspace/testApp/node_modules/ngx-wig/lib/ngx-wig.module.d.ts' imported by the module 'AappModule' in C:/workspace/testApp/src/app/app.mdule.ts'. Please add a @NgModule annotation.

Any tips? 
thanks

**Comment by stevermeister** [comment]
Hi @veteran1 

could you provide you repository reproduce the error and check the cause ?

**Comment by veteran1** [comment]
Hi @stevermeister 
here is a repository https://github.com/veteran1/test-i18n, 
just generate an angular application and add i18n attribute to an html tag then run the command [ng xi18n]

**Comment by stevermeister** [comment]
hm, strange, I've updated ngx-wig to version 10 (compatible with Angular10), but still see an issue in editor (probably related to @veteran1 issue):

<img width="1085" alt="Screenshot 2020-08-03 at 16 25 58" src="https://user-images.githubusercontent.com/1526680/89187609-31804a00-d5a6-11ea-9d25-41b7a5731108.png">

@bampakoa do you know something about it? it looks like an issue that I had somewhere in the past but cannot recall

**Comment by bampakoa** [comment]
@stevermeister I face also the same issue in this repository that I prepare for my talk https://github.com/bampakoa/ngx-wig-electron :smiley: 

I will check it out later today and let you know on the outcome :wink:

**Comment by bampakoa** [comment]
@stevermeister we need to build the library with the `--prod` flag before publishing to npm so that it uses the View Engine (old) compiler.
Currently Angular libraries are not fully compatible with the Ivy compiler https://angular.io/guide/creating-libraries#publishing-your-library

**Comment by stevermeister** [comment]
@bampakoa my bad, I've created a shortcut in package.json and never updated it.

published **ngx-wig@10.0.1**

**Comment by stevermeister** [comment]
@veteran1 please update to ngx-wig@10.0.1, now it should work
