### ISSUE TITLE
Creating custom buttons for version 0.3.6

### ISSUE THREAD

**Issue by sheevam76** [stevermeister/ngx-wig#131]
Hello Team,
I am using ngx-wig 0.3.6 component in my angular 4 project.
My query is how can I create a custom buttons for my text editor like underline, font size, font family, insert table , insert image etc.
I am not finding any way to create them.
Also, I can't upgrade the version as the above versions are not supported with my project.
Can you please help me?

**Comment by stevermeister** [comment]
@sheevam76 I suggest you upgrade your Angular version, 4 is already too old
it's not that difficult you can follow the instructions here - https://update.angular.io/?v=4.0-10.0
