### ISSUE TITLE
Erroneous behavior trying to delete text from the editor

### ISSUE THREAD

**Issue by rd0rnot** [stevermeister/ngx-wig#136]
I'm working on an application where the user can copy and paste from MS-word into our ngx-wig edit field.  We found an issue where hidden field text is not being deleted even if the user presses CTRL-A followed by delete.  This results in our form validation failing to show our required field indicator even though there appears to be no text to the user.

When pasting from Word, it converts the text to HTML with inline CSS styling.  After some work, I've distilled this down to a basic and easily repeatable pattern.

Steps to reproduce:

1. Switch the ngx-wig control to the html preview mode ("Edit" button).
2. Paste the following text into the ngx-wig editor:

```<p><br></p><p>TEST</p>```

3. Click the "Edit" button again to go back to regular editing mode
4. Press CTRL-A to select all text and then press delete.
5. Click the "Edit" button again to go to the HTML preview mode.
6. Notice that the ```<p><br></p>``` text is still there.

Of note, if the first ```<p>``` tag did not have the ```<br>``` inside of it, it would have been deleted as we would expect.  Also, if I had other html code like ```<span></span>``` preceding the ```<p><br></p>``` tag, the delete would fail to remove the preceding span as well as the ```<p><br></p>``` tags.

Found in Chrome and running version 9.0 w/ angular 9.

**Comment by stevermeister** [comment]
@rd0rnot thank you for the detailed report. 
I think it's not about ngx-wig or Angular, but about WYSIWYG itself.
Could you please create a sandbox? I'll look and try to find a lightweight solution for it.

**Comment by rd0rnot** [comment]
Thanks @stevermeister for the reply.  

I've had issues getting a sandbox with the exact versions of angular and ngx-wig to work.  More on that in a moment.

I do have a sandbox based off of one of your demos using an older version of angular and ngx-wig that seems to mostly replicate the issue:

Editor:  https://stackblitz.com/edit/ngx-wig-sample-plugins-p4svlr?file=src/app.ts
App:  https://ngx-wig-sample-plugins-p4svlr.stackblitz.io/

If I use my example in the original bug report in the stackblitz app preview, it retains the ```<br>``` tag after the ctrl-A + delete sequence.  If I run the app in it's own window, I'll see the tags kept as per my report, but the ```<p>``` tag has an extra attribute on it.  Basically, in both scenarios an app would see non-empty field contents which could thwart a custom "is field modified" check.

As for getting a sandbox with the exact versions of Angular and ngx-wig I was using in my custom application (9.1.12 and 9.0.0), I encountered the following console error and I'm not sure why this is:

Error: this.ngxWigEditable is undefined

Here's the sandbox used with the newer Angular and ngx-wig versions:
Editor:  https://stackblitz.com/edit/ngx-wig-sample-plugins-r3xntr?file=src/main.ts
App:  https://ngx-wig-sample-plugins-r3xntr.stackblitz.io

Any idea why this issue is occurring?

**Comment by stevermeister** [comment]
@rd0rnot thank you for providing the example! 
I understood the problem. 
Basically it `ctrl-A` does not select everything. 
And if you do `ctrl-A` -> delete -> backspace (to cleanup the rest) - you will have empty HTML 

I checked several WYSIWYG editors which provide source code option:
https://www.tiny.cloud/
https://summernote.org/
they have the same behavior. 

I also found one that does not have this issue:
https://froala.com/wysiwyg-editor/
but froala is a pretty heavy editor. I would like to keep ngx-wig as light as possible. 

What the criticality of this issue for your project?

**Comment by rd0rnot** [comment]
@stevermeister thanks for the detailed investigation.  It's interesting that this issue is shared amongst several other rich text editors.

To answer your question, this is not a critical issue for us.  We observe it mainly as an anomaly with the required field status we assign to our ngx-wig control, and only when the user does a ctrl-a + delete sequence.

If there is a lightweight solution you can think to apply we would gladly take it, though we certainly wouldn't ask you to make changes that break the control or make it unwieldy to maintain.

Best regards.
