### ISSUE TITLE
Event on blur

### ISSUE THREAD

**Issue by GerkinDev** [stevermeister/ngx-wig#142]
Hi,

I'm trying to capture the `onBlur` event from this component. I could do this with `touched` using reactive forms, but I don't want to use it in my case. Would it be possible to emit a value for an output from [here](https://github.com/stevermeister/ngx-wig/blob/master/projects/ngx-wig/src/lib/ngx-wig.component.ts#L228-L231) ?

Thank you, and cheers ! :beers:

**Comment by bampakoa** [comment]
@GerkinDev the internal `onBlur` method is already wired up with the `touched` property which can be used in both template and reactive forms. So, what is the reason for not using one of them? Could you please elaborate a bit? 

We could of course add another `@Output` property and emit that in the mentioned method but we need to make sure that there is a valid case for doing that 😃 Thank you for using the library 🙏
