### ISSUE TITLE
configure it uses only tags I decide

### ISSUE THREAD

**Issue by ErnestoLopez** [stevermeister/ngx-wig#148]
I only want that "ngx-wig" insert "<br>" when "enter" is clicked its posible that it doesn't add any other tag ?

Thanks in advice

Ernesto

**Comment by bampakoa** [comment]
@ErnestoLopez could you please give more details about what you are trying to achieve?

**Comment by ErnestoLopez** [comment]
I've tried

                ngx-wig {
                    border:1px solid blue; // WORKS
                    width: 100%; // WORKS
                    margin-bottom: 20px; // WORKS
                    .ng-wig {
                        border:1px dashed red!important; // DOESN'T WORKS
                        .nw-toolbar {
                            border:1px solid green!important; // DOESN'T WORKS
                            background-color: pink!important; // DOESN'T WORKS
                            display:none!important; // DOESN'T WORKS
                            visibility: hidden!important; // DOESN'T WORKS
                            border-width: 0!important; // DOESN'T WORKS
                            border: none!important; // DOESN'T WORKS
                            }
                        }

                    } //ngx-wig

inside a scss of an ionic page (that should not influence, I think)

thanks 

Ernesto

**Comment by ErnestoLopez** [comment]
sorry for my english, maybe I have not explained myself well

what I want is for ngx-wig to only enter the tag <br> when the user hits enter
That no other tag can be used for now, later, if possible, I would add them little by little.

Thanks.

**Comment by bampakoa** [comment]
@ErnestoLopez I do not think this is something that you can customize to the editor. However, one possible solution would be to detect the `<div><br></div>` sequence and replace it accordingly.
