### ISSUE TITLE
Where is version 12 of the npm package? 

### ISSUE THREAD

**Issue by NZE** [stevermeister/ngx-wig#154]
https://www.npmjs.com/package/ngx-wig?activeTab=readme 

Looks like there is no version 12 for ng12?

**Comment by stevermeister** [comment]
@NZE thx! fixed!

**Comment by stevermeister** [comment]
hope this will fix the problem for all next releases - https://github.com/stevermeister/ngx-wig/pull/155

**Comment by NZE** [comment]
Thanks Steve
