### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by paul-henriz** [stevermeister/ngx-wig#156]
Hi,

Do you have an ETA for a new release supporting Angular 13?

Best thanks

**Comment by stevermeister** [comment]
@paul-henriz thank you for your question.
not yet. I'm working on it right now

**Comment by stevermeister** [comment]
PR is there - https://github.com/stevermeister/ngx-wig/pull/157

**Comment by paul-henriz** [comment]
Thank you very much for your reactivity!
