### ISSUE TITLE
Remove legacy code

### ISSUE THREAD

**Issue by Akxe** [stevermeister/ngx-wig#162]
https://github.com/stevermeister/ngx-wig/blob/5f271e70fd1e06d411f14ce7b3c80ef0fbeaa79f/projects/ngx-wig/src/lib/ngx-wig.component.ts#L121:L123

This could be removed since IE is no longer supported from Angular itself

**Comment by stevermeister** [comment]
@Akxe thanks for the hint! 

https://github.com/stevermeister/ngx-wig/pull/165/files
