### ISSUE TITLE
<br> tag left after textarea clear

### ISSUE THREAD

**Issue by kucherovst** [stevermeister/ngx-wig#168]
There's an issue when I'm pasting formatted text in the textarea and then delete it the `<br>` tag left as a value of this field. I see that ngx-wig work with content as a string, so the first thing that comes to mind is regexp that will cut empty tags somehow, but maybe there's a better/more universal solution.

https://user-images.githubusercontent.com/104344190/168632442-a3bb50ef-15f5-4269-8fde-b3be81b56d76.mp4

**Comment by stevermeister** [comment]
yes, indeed. 
thank you for reporting! 
do you want to make a PR for it?

**Comment by stevermeister** [comment]
closed by https://github.com/stevermeister/ngx-wig/pull/169
