### ISSUE TITLE
Improve documentation about custom buttons.

### ISSUE THREAD

**Issue by hodzanassredin** [stevermeister/ngx-wig#171]
Now it is not clear from documentation how to add custom buttons to implement some behavior with state manipulations.
For example: how can we implement undo, redo buttons?

Now I'm using this code(not an expert in angular)

 
```
 @ViewChild('ngx', {static: false})
    ngx: NgxWigComponent;
    @Input()
    content = 'sss';
    inputStates: string[] = [];
    undoStats = 0;
    ngAfterViewInit(): void {
      this.ngx.toolbarButtons.push({
          label: 'Undo',
          title: 'Undo',
          command: (ctx: NgxWigComponent) => {
            this.undo();
          },
          styleClass: 'nw-button',
          icon: 'icon-custom'
        });
      this.ngx.toolbarButtons.push({
          label: 'Redo',
          title: 'Redo',
          command: (ctx: NgxWigComponent) => {
            this.redo();
          },
          styleClass: 'nw-button',
          icon: 'icon-custom'
        });
  }
```

**Comment by MPapini91** [comment]
Not just something to undo-redo editing?
`undo: {
    label: 'Undo',
    title: 'Undo',
    command: 'undo',
    styleClass: 'nw-button',
  },
  redo: {
    label: 'Redo',
    title: 'Redo',
    command: 'redo',
    styleClass: 'nw-button'
  }`

**Comment by stevermeister** [comment]
@hodzanassredin thank you for your question, do you want to add it to the documentation?

I mean solution from @MPapini91

**Comment by hodzanassredin** [comment]
> undo: { label: 'Undo', title: 'Undo', command: 'undo', styleClass: 'nw-button', }, redo: { label: 'Redo', title: 'Redo', command: 'redo', styleClass: 'nw-button' }

I don't understand how does it work. I can't find where these commands are described in the source code of ngx-wig. Could you please clarify?

**Comment by MPapini91** [comment]
Ok, to add custom buttons you can follow [this](https://stackblitz.com/edit/ngx-wig-sample-plugins?file=src%2Fapp.ts) example from documentation (I quite didn't understand your approach sorry) and add to the variable `MY_PLUGIN` your custom buttons, like:

```
const MY_PLUGIN = {
  edithtml: {
    label: 'Custom button',
    title: 'Custom button',
    command: (ctx: NgxWigComponent) => {
      alert('This is a custom button');
    },
    styleClass: 'nw-button',
    icon: 'icon-custom',
  },
  undo: {
    label: 'Undo',
    title: 'Undo',
    command: 'undo',
    styleClass: 'nw-button',
  },
  redo: {
    label: 'Redo',
    title: 'Redo',
    command: 'redo',
    styleClass: 'nw-button',
  },
};
```

If you want a reference to the source code, I think you can look to the example app in [src/app/app.module.ts](https://github.com/stevermeister/ngx-wig/blob/master/src/app/app.module.ts) and add the same code for undo redo in the `DEFAULT_LIBRARY_BUTTONS` variable (but I didn't try so better ask to @stevermeister )

**Comment by MPapini91** [comment]
Ah, for the `command` you can pass a function or a command from [this list](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand)
