### ISSUE TITLE
Implement plugins mechanism

### ISSUE THREAD

**Issue by bampakoa** [stevermeister/ngx-wig#18]
We need to answer the following questions for implementing a mechanism that will register and load plugins in the main editor:

1. What kind of instance a plugin should be.
2. How to register a plugin.

There is a related question in SO https://stackoverflow.com/questions/44654508/angular-creating-plugins-for-3rd-party-packages-libraries.

Possible solutions could be:

- `forRoot`: used by convention to configure a module's providers
- Component discovery and dynamically load (not so robust, needs a way to know the type of the actual plugin in order to load it)
- A [nice implementation](https://www.ag-grid.com/ag-grid-angular2-support-v7/) from guys in **ng-grid**

**Comment by bampakoa** [comment]
@stevermeister any thoughts on that?

**Comment by stevermeister** [comment]
@bampakoa let's make it stable get 100 starts and after return back to this topic
I want to be sure that core is stable enough for future extentions

**Comment by bampakoa** [comment]
@stevermeister [this](https://github.com/maximusk/extension-mechanism-demo) seems like a good resource for that. It was presented in ng-conf earlier https://www.youtube.com/watch?v=pERhnBBae2k

**Comment by stevermeister** [comment]
I watched it twice, the concept is too abstract. 

As far as I understand the idea is about reimplementation of lazy loading module mechanism?

I know speaker in person, will ask his opinion

**Comment by bampakoa** [comment]
Yes, it tries to mimic the operation of the Angular router. That guy has a very good knowledge of Angular in depth and I thought that it should be a good idea if he proposes such a solution.

**Comment by bampakoa** [comment]
@stevermeister I recently came across [this](https://youtu.be/q2Exs-82tkw?t=1557) video from Angular Connect 2018 that demonstrates an alternate way of introducing plugins in an Angular app.

**Comment by stevermeister** [comment]
@bampakoa 

it's about Dynamic components, to use router dynamic module loader to do lazy loading for component (that is wrapped into module)

it's nice, BUT 
in previous version of editor with AngularJS we were able to change properties of core module like changing set of buttons. and here is not that easy to inject a *virtual* service.

anyway I'll have a second look, thx for sharing the idea!

**Comment by stevermeister** [comment]
@bampakoa 

Now I'm working in branch https://github.com/stevermeister/ngx-wig/tree/brand-new and before going to plugins decided to update the whole env (based on new ng-cli library generator)

You are welcome to join. 
Also I decided to rebuild the idea of icon dependancy - so to build version without dependancy on mdi at all

**Comment by stevermeister** [comment]
@bampakoa I'm still thinking what would be the best way to implement plugins.

From user side now considering this options: 

1. ```ngxWig.forRoot( { buttonsConfig })```
2. Just use service for toolbar (in component controller):
```NgxToolbarSerice.addCustomButton('image', ImageButton)```
3. Use flag multi to extend provider:
```{ provide: customButtons, useValue: ImageButtonComponent, multi: true }```

what do you think?
for now we are speaking only about plugins to implement extra button

**Comment by bampakoa** [comment]
@stevermeister yes, this looks the most robust solution to me so far!

**Comment by stevermeister** [comment]
I mean took the best our of 3 :)

**Comment by bampakoa** [comment]
@stevermeister let me shed some light here :smiley: I had a chat with one of Angular core team members and explained our situation. Theoretically, they proposed to go with the first method, which is the defacto for such cases, and avoid the other two. They also advised to test it under AoT and possibly lazy-load mode.

**Comment by stevermeister** [comment]
@bampakoa great! I hope I'll have time to finish first version of it

**Comment by stevermeister** [comment]
@bampakoa now I'm thinking about format for config 

`ngxWig.forRoot( { buttonsConfig })`

**Comment by stevermeister** [comment]
@bampakoa 
ok, I've implemented first version with an option to add config, please have a look

**Comment by stevermeister** [comment]
for now I'll close this one till the moment we collect enough info to think about what kind of plugins we need
