### ISSUE TITLE
Angular 15 support

### ISSUE THREAD

**Issue by PhilFlash** [stevermeister/ngx-wig#191]
Is support for Angular 15 on the roadmap for this project?

I have error for angular 15:
npm ERR! Found: @angular/common@15.1.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"15.1.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^14.0.5" from ngx-wig@14.0.7
npm ERR! node_modules/ngx-wig
npm ERR!   ngx-wig@"14.0.7" from the root project

Philippe

**Comment by stevermeister** [comment]
@PhilFlash sorry, for some reason I thought that it was already updated

**Comment by stevermeister** [comment]
@bampakoa need you help if you know the issue. 

trying to publish new version, but getting an error:
```
'ERROR: Trying to publish a package that has been compiled by Ivy in full compilation mode. This is not allowed.\nPlease delete and rebuild the package with Ivy partial compilation mode, before attempting to publish.\n'
```

**Comment by PhilFlash** [comment]
Try to add  "compilationMode": "partial" in tsconfig.lib.json and tsconfig.lib.prod.json

in projects/ngx-wig/tsconfig.lib.json
>>>>
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "declarationMap": true,
    "module": "es2020",
    "declaration": true,
    "sourceMap": true,
    "inlineSources": true,
    "types": [],
    "lib": [
      "dom",
      "es2020"
    ]
  },
  "angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableResourceInlining": true,
    "compilationMode": "partial"
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}
<<<<

projects/ngx-wig/tsconfig.lib.prod.json
>>>>
{
  "extends": "./tsconfig.lib.json",
  "compilerOptions": {
    "declarationMap": false
  },
  "angularCompilerOptions": {
    "compilationMode": "partial"
  }
}
<<<<

**Comment by stevermeister** [comment]
@PhilFlash thx! it looks like it works.

but now I faced another issue, an even more strange one: 

> Not Found - PUT https://registry.npmjs.org/ngx-wig - Not found

I logged in, so it's not an auth issue

**Comment by stevermeister** [comment]
![Screenshot 2023-02-05 at 11 44 44](https://user-images.githubusercontent.com/1526680/216814464-4664b413-c1d1-47e7-8f38-b99e198c93af.png)

**Comment by stevermeister** [comment]
ok, after some research I found that it still was a problem with authorisation. anyway it's solved now and 
**version 15.1.4 has been published!** 

@PhilFlash please check

**Comment by PhilFlash** [comment]
Hi Stepan,
All is ok for me.
