### ISSUE TITLE
List and html options do not work in redactor

### ISSUE THREAD

**Issue by KashaevaD** [stevermeister/ngx-wig#28]
When select something and trying to create, for example, ordered list - nothing happens
![out-2](https://user-images.githubusercontent.com/25029796/32895032-5e8fe70c-cae7-11e7-9935-879c1959227d.gif)

**Comment by stevermeister** [comment]
@KashaevaD I think it would be nice to describe the reason of the issue in your specific case instead of just closing it

**Comment by KashaevaD** [comment]
The problem was about that in current project we have  custom-normalize styles where we wiped the standard styles of lists
`ol, ul {
  list-style: none;
  padding-left: 0;
}`

**Comment by stevermeister** [comment]
👍
