### ISSUE TITLE
How to focus on the container ?

### ISSUE THREAD

**Issue by AdamAnandUS** [stevermeister/ngx-wig#29]
Hello,

As soon as I load the "ngWig" component, the focus goes to the first button on the toolbar. Instead I want the focus to be on the container so that the user can start typing in right away.

How can I achieve this ? Please suggest.

I am using version. -- ngx-wig@0.3.3

Thanks
Adam

**Comment by bampakoa** [comment]
@AdamAnandUS AFAIK it is not supported out of the box. So, you can use `ViewChild` to get a reference of the actual HTML container element and then call `focus()`. See [this](https://stackblitz.com/edit/ngx-wig-focus) sample for more details.

**Comment by stevermeister** [comment]
@bampakoa what do you think about idea always keeping the focus on edit container?

**Comment by bampakoa** [comment]
@stevermeister I think this would have side effects. Imagine what is going to happen with more than one editor on a page (I have noticed that a lot of users, use the editor like this).

**Comment by stevermeister** [comment]
true
