### ISSUE TITLE
Metadata mismatch

### ISSUE THREAD

**Issue by ZuSe** [stevermeister/ngx-wig#38]
When I try to compile my project with AOT it throws:
/node_modules/ngx-wig/ngx-wig.d.ts, found version 4, expected 3

normal build runs fine.

Using ngx-wig 1.0-rc7 with SystemJS 0.19 and TS 2.3.4

**Comment by stevermeister** [comment]
@ZuSe thank you for reporting we will try to figure out.

**Comment by bampakoa** [comment]
@ZuSe Have you tried to update to the latest version?

**Comment by stevermeister** [comment]
@ZuSe please try the latest version
