### ISSUE TITLE
playground does not work

### ISSUE THREAD

**Issue by stevermeister** [stevermeister/ngx-wig#40]
I just cloned fresh version and playground does not work: it does not find/compile/place index.js file.

@bampakoa after quick investigation I did not find the place, maybe you have an idea?

**Comment by bampakoa** [comment]
It seems that [this](https://github.com/stevermeister/ngx-wig/blob/master/playground/index.ts#L9) line causes the problem but I have not find why this is happening.

**Comment by stevermeister** [comment]
I think it's something with systemjs

**Comment by bampakoa** [comment]
If you use the UMD module, it will create the `index.js` file inside **.playground** folder. 😕

**Comment by stevermeister** [comment]
fixed
