### ISSUE TITLE
White space(s) added on focus

### ISSUE THREAD

**Issue by ilDon** [stevermeister/ngx-wig#46]
First thanks for the great editor, it was precisely what I was looking for :-)

I am using the editor in an Angular 5 app within a reactive form and I noticed that `onFocus` the editor adds a white space if the value passed to the editor is `=== undefined || '' || null || false || 0` (even if the value to be passed has to be a string, I've tried with other non-string values to test the behaviour). 

For simplicity, I've included an example: [https://stackblitz.com/edit/ngx-wig-2-way-binding-jhdpay?embed=1&file=app/app.component.html](https://stackblitz.com/edit/ngx-wig-2-way-binding-jhdpay?embed=1&file=app/app.component.html).

I've forked the example from the ngModel one, and I can confirm that the issue is present also when passing the value via `[content]="somevalue"`.

My problem is that I'm also assigning to the `FormData` element a `required` validator, and the fact that a white space is added breaks the validator as it thinks that some value has been entered.

As of now I've solved the issue by using `contentChange` to call a method that calls `trim()` on the value and then I call `formData.patchValue({ myEditorValue: trimmedValue })`. I have not included this code in the example for simplicity.

**Comment by stevermeister** [comment]
could you please check now with updated version 1.2.2?

**Comment by ilDon** [comment]
Yes, no added spaces in v. 1.2.2! :-)
