### ISSUE TITLE
doesn't work with a formControlName in a material2 reactive form

### ISSUE THREAD

**Issue by akolybelnikov** [stevermeister/ngx-wig#49]
neither value accessor cannot be established, nor can mat-form bind to the form control, if used as:

`<mat-form-field><ngx-wig [formControlName]="name"></ngx-wig></mat-form-field>`

possibly needs to be created as a cutom form field control:
https://material.angular.io/guide/creating-a-custom-form-field-control

**Comment by stevermeister** [comment]
is it still the case for 1.2.2?
could I ask you to make a stackblitz for it?

**Comment by akolybelnikov** [comment]
I have tried to implement it as in the following stackblitz example: 

https://stackblitz.com/angular/earajmpqaoxx

but I have not succeded yet. For the time being I am not putting ngx-wig in a mat-form-field but use it in the same form, and it works. Styling and validation can be done separately.

**Comment by alexshakura** [comment]
@akolybelnikov there is a distinct npm package for material - https://www.npmjs.com/package/mat-ngx-wig
