### ISSUE TITLE
Awesome module, supports SSR, but...

### ISSUE THREAD

**Issue by cbernth** [stevermeister/ngx-wig#64]
It works out of the box with SSR (Server Side Rendering using angular 5.2.9) which makes it unique among all other wysiwyg editors I've tested so far.

I'm currently investigating which editor module to use for a new project feature and I, by far, favor ngx-wig so far. However, I have a few concerns - sorry for wording them very directly - but I hope getting them answered will benefit all potential users of ngx-wig:

- Is development still ongoing for this project? (I see very low activity lately) 
- Are there any plans to fix the current issue with one button not showing up and the failing builds?
- Will more simple features be added (indentation, text alignment)?

I would not mind being a contributor if this module is still planned to move forward.

Thanks :)

**Comment by stevermeister** [comment]
Thank you for kind words!

- yes
- yes
- maybe, we want to keep it as light as possible.

Currently, we are using ngx-wig for several applications of our product and try to fix all the bugs. But it's never enough time to do all the nice adjustments and fix tests, so if you want to contribute you are welcome!
