### ISSUE TITLE
Property '_onContentChange' is private and only accessible within class 'NgxWigComponent'.

### ISSUE THREAD

**Issue by IainAndrew** [stevermeister/ngx-wig#66]
Hi,

I'm getting this error when running `ng-build --prod`:

`ERROR in node_modules/ngx-wig/ngx-wig.d.ts.NgxWigComponent.html(1,1383): : Property '_onContentChange' is private and only accessible within class 'NgxWigComponent'.`

It looks like `_onContentChange` is a private member when it should be public?

Thanks,
Iain

**Comment by stevermeister** [comment]
@IainAndrew thank you for the feedback! it's fixed now in version 1.2.7
