### ISSUE TITLE
Size of the Field

### ISSUE THREAD

**Issue by cbanzet** [stevermeister/ngx-wig#67]
Is it possible to change the size of the ngx-wig area.

I tried to do it with css :

.nw-editor {
  height: 100px !important;
}

But it doesn't work as I'm doing it from another component.

**Comment by bampakoa** [comment]
@cbanzet If your component is the host of the editor, you need to use the `::ng-deep` combinator.

```
::ng-deep .nw-editor {
  height: 100px !important;
}
```

**Comment by cbanzet** [comment]
thanks a lot @bampakoa
