### ISSUE TITLE
Is it reasonable to make ngx-wig compatiple to use inside a mat-form-field

### ISSUE THREAD

**Issue by hungcao181** [stevermeister/ngx-wig#71]
I am trying to use ngx-wig inside my material angular app. This seem to work as an independent input that I wrapped inside a div.
To get a consistent experience with other fields on a material form, it might be better to be able to wrap ng-wig inside a mat-form-field directive.

Google have instruction to do so https://material.angular.io/guide/creating-a-custom-form-field-control.

Anyone have thought or even a try?

**Comment by stevermeister** [comment]
We are working on it...

**Comment by alexshakura** [comment]
hey @hungcao181, right now I'm working on it, there will be distinct library with ngx-wig as a dependency with already-made styles

**Comment by alexshakura** [comment]
@hungcao181 @stevermeister check it out https://www.npmjs.com/package/mat-ngx-wig
