### ISSUE TITLE
Adding custom buttons

### ISSUE THREAD

**Issue by DMarinsa** [stevermeister/ngx-wig#73]
Is it possible to add custom buttons to the editor bar?

**Comment by bampakoa** [comment]
This is not currently possible. Have a look at #18

**Comment by stevermeister** [comment]
@DMarinsa yes now it's possible, by providing specific config:
```
{ provide: BUTTONS, multi: true, useValue: CUSTOM_LIBRARY_BUTTONS },
```

check an example here - https://github.com/stevermeister/ngx-wig/pull/95/files#diff-c12d74ca8cc105ab72f388747ca666c8R63

**Comment by wafae1234** [comment]
@stevermeister please how can i set Edit HTML button to enable editMode initially, i did this :
const CUSTOM_LIBRARY_BUTTONS = {
  edithtml: {
    label: '</>',
    title: 'Edit HTML',
    command: (ctx: NgxWigComponent) => {
      ctx.editMode = true;
    },
    styleClass: 'nw-button--source',
    icon: '',
  }
};

but editor initialyze ctx.editMode with false

**Comment by stevermeister** [comment]
@wafae1234 I think for you case `editMode` should be provided like an optional @Input()
instead of just putting `false`

do you want to do a PR for it?

**Comment by wafae1234** [comment]
what do you mean by PR ?
Where can i put @input(), excuse my ignarance i m new to angular
here is my component view:
`<ngx-wig [formControl]="editorControl" [placeholder]="placeholder + (required ? ' *' : '')"></ngx-wig>`

 and the CUSTOM_LIBRARY_BUTTONS value is provided in the module ; 

`import { A11yModule } from '@angular/cdk/a11y';
import { CommonModule } from '@angular/common';

import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { NgxWigModule, NgxWigComponent, BUTTONS } from 'ngx-wig';

import { MatNgxWigComponent } from './mat-ngx-wig/mat-ngx-wig.component';

const CUSTOM_LIBRARY_BUTTONS = {
  edithtml: {
    label: '</>',
    title: 'Edit HTML',
    command: (ctx: NgxWigComponent) => {
      // ctx.editMode = !ctx.editMode;
      ctx.editMode = true;

    },
    styleClass: 'nw-button--source',
    icon: '',
  }
};

@NgModule({
  imports: [
    A11yModule,
    CommonModule,
    MatFormFieldModule,
    MatInputModule,
    NgxWigModule,
    ReactiveFormsModule,
  ],
  declarations: [MatNgxWigComponent],
  exports: [MatNgxWigComponent],
  providers: [
    { provide: BUTTONS, multi: true, useValue: CUSTOM_LIBRARY_BUTTONS },
  ]
})
export class MatNgxWigModule { }
`

**Comment by wafae1234** [comment]
what do you mean by PR ?

Where can i put @input(), excuse my ignorance i m new to angular
here is my component view:
`<ngx-wig [formControl]="editorControl" [placeholder]="placeholder + (required ? ' *' : '')"></ngx-wig>`

 and the CUSTOM_LIBRARY_BUTTONS value is provided in the module ; 

```
import { A11yModule } from '@angular/cdk/a11y';
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { NgxWigModule, NgxWigComponent, BUTTONS } from 'ngx-wig';

import { MatNgxWigComponent } from './mat-ngx-wig/mat-ngx-wig.component';

const CUSTOM_LIBRARY_BUTTONS = {
  edithtml: {
    label: '</>',
    title: 'Edit HTML',
    command: (ctx: NgxWigComponent) => {
      ctx.editMode = true;
    },
    styleClass: 'nw-button--source',
    icon: '',
  }
};

@NgModule({
  imports: [
    A11yModule,
    CommonModule,
    MatFormFieldModule,
    MatInputModule,
    NgxWigModule,
    ReactiveFormsModule,
  ],
  declarations: [MatNgxWigComponent],
  exports: [MatNgxWigComponent],
  providers: [
    { provide: BUTTONS, multi: true, useValue: CUSTOM_LIBRARY_BUTTONS },
  ]
})
export class MatNgxWigModule { }
```

**Comment by stevermeister** [comment]
> PR
I meant a Pull Request to change the library itself. 

I don't think that there is a possibility to do so in the current setup. 

@bampakoa what do you think?

**Comment by bampakoa** [comment]
@stevermeister @wafae1234 the only way to access the `editMode` property and change it, is using the `ViewChild` decorator such as in the following snippet:

```ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { NgxWigComponent } from 'ngx-wig';

export class AppComponent implements OnInit  {

  @ViewChild(NgxWigComponent) editor: NgxWigComponent;
  
  ngOnInit() {
    this.editor.editMode = true;
  }
}
```

**Comment by wafae1234** [comment]
@stevermeister @bampakoa thank you for the help, i will try this one.
please another question, we have a project that uses angular 6 and i want to use ngx-wig 1.6.0 as a text editor, i did copy past the config Above but the editor tells that '"ngx-wig"' has no exported member named 'BUTTONS'

**Comment by wafae1234** [comment]
@stevermeister @bampakoa thank you for the help, i will try this one.
please another question, we have a project that uses angular 6 and i want to use ngx-wig 1.6.0 as a text editor, i have copied pasted the config above but the editor tells that '"ngx-wig"' has no exported member named 'BUTTONS'
how can i set buttons in  ngx-wig 1.6.0 ?
