### ISSUE TITLE
How to set focus/cursor at the end of the content or at the last position where cursor was?

### ISSUE THREAD

**Issue by mayur9293** [stevermeister/ngx-wig#74]
Hi,
I am trying to add tags to the editor in 2 ways.
1. How to get the cursor position and add some text to that position. Eg. If i am trying to change the ngModel from typescript the cursor position is set automatically to 0th character or start. ~~If the user has written a paragraph and now he tries to annotate it with the hashtags given below the editor.~~ Is there a way to insert it in between based on cursor position?? ~~I did it to append in the end but~~ Can it be done in between?? Demo is shown [here](https://stackblitz.com/edit/angular-muxedl).

2.  ~~If user types '#' followed by tag and space, the content will be converted to a tag, where I am applying bootstrap 4 css to it.~~ Demo is shown [here](https://stackblitz.com/edit/angular-muxedl). But when the ngModel is changed from the typescript the cursor position is changed to the start. I tried using #29 but the same behavior is seen. So is there any way to keep the focus of cursor where it was or the last position??

Any help on these 2 points will be really appreciated. :)

**Comment by mayur9293** [comment]
I tried using `@HostListener` over the ngx-wig to get the `selectionStart` or the cursor's position. Which works absolutely fine on TextArea. But it returns `undefined` for ngx-wig.

The sample code looks something like this


```
@Directive({
     selector: '[TagGenerator][ngModel]'
})
export class TagGeneratorDirective {
@Output() ngModelChange: EventEmitter<any> = new EventEmitter();
     constructor(private el: ElementRef, private render: Renderer) { }

@HostListener('keyup', ['$event']) onInputChange(event) {
    // get position
    let pos = this.el.nativeElement.selectionStart;
    let val = this.el.nativeElement.value;
    if (SomeLogic) {
      // Change ngModel here
      this.render.setElementProperty(this.el.nativeElement, 'value', val);
      this.ngModelChange.emit(val);
      // set the cursor position to old place
      setTimeout(() => {
          this.el.nativeElement.selectionStart = pos;
          this.el.nativeElement.selectionEnd = pos;
    });
    }
  }
```

Where I am using this directive something like this
`<ngx-wig [(ngModel)]="value" TagGenerator [buttons]="'bold,italic'" >loading</ngx-wig>`

Am I doing something wrong? Any help would be appreciated.

**Comment by bampakoa** [comment]
@mayur9293 try to set the caret at the end with the following snippet:

```
const el = this.editor.ngxWigEditable.nativeElement;
      setTimeout(() => {
        var range = document.createRange();
        range.selectNodeContents(el);
        range.collapse(false);
        var sel = window.getSelection();
        sel.removeAllRanges();
        sel.addRange(range);
      });
```

**Comment by mayur9293** [comment]
> @mayur9293 try to set the caret at the end with the following snippet:
> 
> ```
> const el = this.editor.ngxWigEditable.nativeElement;
>       setTimeout(() => {
>         var range = document.createRange();
>         range.selectNodeContents(el);
>         range.collapse(false);
>         var sel = window.getSelection();
>         sel.removeAllRanges();
>         sel.addRange(range);
>       });
> ```
This worked like magic.
Is there a way to set the caret in between or towards the previous position??
