### ISSUE TITLE
[WIP] Brand new version

### ISSUE THREAD

**Issue by stevermeister** [stevermeister/ngx-wig#76]
- [x] update angular-cli env
- [x] remove icons dependancy
- [x] make tests great again
- [x] implement plugins (https://github.com/stevermeister/ngx-wig/issues/18)

**Comment by stevermeister** [comment]
https://github.com/stevermeister/ngx-wig/tree/brand-new

**Comment by bampakoa** [comment]
@stevermeister I am bit confused. I can see the task **remove icons dependency** on the checklist but on the other hand you have added **FontAwesome** in the branch :confused:

**Comment by stevermeister** [comment]
>  but on the other hand you have added FontAwesome in the branch

true, that's why checkbox still not checked :)

I did not find the way to make it nice and simple quickly. FontAwesome package was fastest solution. It's definitely better than just including in index.html. But it does not mean that it stay in final realise. For now it's temporary solution that allows us to move forward. If you have elegant and simple way to output buttons - please share.

> Also I spotted a commented expect statement

Changed PR to [WIP]

**Comment by stevermeister** [comment]
@bampakoa 

removing dependency - https://github.com/stevermeister/ngx-wig/pull/78

**Comment by bampakoa** [comment]
@stevermeister what do you think about providing a schematic also for the new version?

**Comment by stevermeister** [comment]
hm, quite interesting option!

I was also thinking about schematics, but did not find a use (just to import to main module was not really an option)

**Comment by bampakoa** [comment]
😃 Cool! We could even pass default buttons though the schematic 😉

**Comment by bampakoa** [comment]
What do you think about `ng add @ngx-wig/ngx-wig --buttons=bold,italic` ? Or we could use their titles `buttons=B,UL`

**Comment by stevermeister** [comment]
hm, not very convenient.
I'm thinking about prompt with multi-select, but angular-cli is not supporting it yet
