### ISSUE TITLE
How to integrate at.js(atwho) library with ngx-wig.

### ISSUE THREAD

**Issue by mayur9293** [stevermeister/ngx-wig#82]
Referring to [at.js](http://ichord.github.io/At.js/) how to integrate it with ngx-wig

are there any initialization events where we can probably add this? [see this](https://github.com/froala/angular-froala-wysiwyg/issues/12)

**Comment by stevermeister** [comment]
could you provided a sandbox what you have already tried?

**Comment by mayur9293** [comment]
After lots of hit trials and run I finally managed to integrate at.js (Probably not the most appropriate way) for enabling ngx-wig to have auto-suggest feature the prototype can be found [here](https://stackblitz.com/edit/angular-dqmhkt)

Well some new questions surrounding this integration.
1. If the User types **_#_** (auto suggest List appears) user clicks it. It appears on the dom but the data is not getting bind to the model (Check  [demo](https://stackblitz.com/edit/angular-dqmhkt)). Is there a way to do so explicitly from some function?
2. Is the approach used for integrating this be made in a better way?? Like not using the class name and ngAfterViewInit for doing so.

Any help would be really appreciated.

**Comment by stevermeister** [comment]
i would suggest to look into angular way of doing things 
like https://github.com/YazanAabeed/at-who-angular
not jQuery one
