### ISSUE TITLE
Toggle to view HTML

### ISSUE THREAD

**Issue by smitchell** [stevermeister/ngx-wig#87]
Are there plans to allow a button to toggle to HTML like Froala does? We are using ngx-wig now, and the user asked me to enable the "<>" button to see what is going wrong with the markup.  For now, I could flip them into a text area.

**Comment by bampakoa** [comment]
@smitchell you can set `isSourceModeAllowed` property of the `ngx-wig` to `true` and a new button with a pencil icon will appear at the end of the toolbar.

**Comment by andreElrico** [comment]
Not sure whether APIs have changed, `isSourceModeAllowed` does not exist;

Here is one way of achieving what you want. 

https://stackblitz.com/edit/ngx-wig-sample-plugins-supbgz?file=src%2Fapp.ts

+ overLoading "edithtml" for BUTTONS injection token
+ some css wizardry
