### ISSUE TITLE
Type 'ModuleWithProviders' is not generic.

### ISSUE THREAD

**Issue by storytellerr** [stevermeister/ngx-wig#93]
i am getting this error in angular 6

ERROR in node_modules/ngx-wig/lib/ngx-wig.module.d.ts(7,9): error TS2315: Type 'ModuleWithProviders' is not generic.
node_modules/ngx-wig/lib/ngx-wig.module.d.ts(8,24): error TS2315: Type 'ModuleWithProviders' is not generic.

**Comment by stevermeister** [comment]
could you make stackblitz sandbox for it?

based on this one - https://stackblitz.com/edit/ngx-wig-sample1?file=src/app/app.component.ts
