### ISSUE TITLE
No icon is showing for buttons

### ISSUE THREAD

**Issue by storytellerr** [stevermeister/ngx-wig#94]
i am using angular 6 and icons are not showing on buttons. this issue is coming in all old version including 1.6.0 and 1.0.3. 
![Screenshot from 2019-04-25 13-57-15](https://user-images.githubusercontent.com/15611406/56721939-9b833000-6763-11e9-9c28-1f7ee03455f6.png)

**Comment by stevermeister** [comment]
could you make stackblitz sandbox for it?

based on this one - https://stackblitz.com/edit/ngx-wig-sample1?file=src/app/app.component.ts

**Comment by storytellerr** [comment]
@stevermeister icons are visiable in  toolbar when version is 2.0.1. but in my project i am using angular 6(can't update to angular 7) and version 1.6.0 has a bug of not showing icons in toolbar. 

here is stackblitz - https://stackblitz.com/edit/angular-8v7qnw

**Comment by stevermeister** [comment]
I got the point, so it's nothing to do with Angular6.
For version 1.6 and lower icons were not prebuild in library and you had to include them into your project yourself

**Comment by storytellerr** [comment]
is there any standard(name, size, etc) ? how to include them any doc or info ?

**Comment by stevermeister** [comment]
you can just use CDN - https://stackblitz.com/edit/angular-1njhzk?file=src%2Findex.html

**Comment by storytellerr** [comment]
works like a charm :sparkles:. thanks
