### ISSUE TITLE
Plan for Angular 8 Support?

### ISSUE THREAD

**Issue by tettsuan** [stevermeister/ngx-wig#96]
I would like to upgrade my angular-7 project to angular-8.
Do you have a plan for upgrading it to support angular-8? If not, how can I help with it?
I have cloned the master-branch and locally upgraded to angular8. Unittests were through with small modification.
Shall I create a new branch and push it and create merge request?
Also I would like to know how I can test it with my local app(s).

**Comment by stevermeister** [comment]
sure, I would. 
not always have time for it.

> Shall I create a new branch and push it and create merge request?
it would be fantastic!

> Also I would like to know how I can test it with my local app(s).
you can build npm package locally(https://github.com/stevermeister/ngx-wig/blob/master/package.json#L11) and import it to your project (instead of npm one)

**Comment by tettsuan** [comment]
.. and I was not allowed to push..

**Comment by stevermeister** [comment]
here you can find information how to do pull requests - https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

> But it doesn't work with angular7. it says
it's not good. ideally to keep backwards compatibility with previous version

**Comment by tettsuan** [comment]
it was a stupid mistake... my project was original with angular6 and upgraded to angular7. That time it wasn't a problem and therefore ngx-wig package remained with an old version (1.6!!).
I've upgraded it to 2.1.1 and has no problem at all.. sorry that i've bothered you.
