### ISSUE TITLE
Is plugins mechanism ready yet?

### ISSUE THREAD

**Issue by darshanDevrai** [stevermeister/ngx-wig#97]
First of all thank you so much for the awesome ngx-wig.
I want to add plugins for image, header, alignment and code in my editor. 
Here in [this](https://github.com/stevermeister/ngx-wig/issues/76 ) issue, the checkbox of **Implement Plugins Mechanism** is **checked**  . 
So is it ready yet? If yes then how to use it?

Thank you :)

**Comment by stevermeister** [comment]
yes, it's ready in terms of buttons, now you can create any button you like
you can check it here - https://github.com/stevermeister/ngx-wig/issues/73
